version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:17.0  # CircleCI official Java 17 image
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Pull your code from GitHub
      - run:
          name: Show Java version
          command: java -version

      - run:
          name: Build app with Maven wrapper
          command: |
            chmod +x mvnw
            ./mvnw clean package -DskipTests

      - setup_remote_docker


      - run:
          name: Build Docker image
          command: |
            docker build -t springboot-devops-demo .

      # Optional: test Docker image locally
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

