jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "your-key-fingerprint-if-using-circleci's SSH keys"
      - run:
          name: Save private key
          command: |
            echo "$EC2_PRIVATE_KEY" > ec2-key.pem
            chmod 600 ec2-key.pem
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << EOF
              docker pull djdevops2025/springboot-devops-demo:latest
              docker stop \$(docker ps -q --filter ancestor=djdevops2025/springboot-devops-demo:latest) || true
              docker rm \$(docker ps -aq --filter ancestor=djdevops2025/springboot-devops-demo:latest) || true
              docker run -d -p 8081:8081 djdevops2025/springboot-devops-demo:latest
            EOF

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
            
